FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# No need to copy source files as we'll use a volume mount

EXPOSE 3000

# Start in development mode with hot reloading
CMD ["npm", "start"]
