services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password123}

      # Hot reload
      - CHOKIDAR_USEPOLLING=true
      
    ports:
      - "27017:27017"

  server:
    build: ./server
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - DATABASE_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017/saas-template?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_at_least_32_characters_long}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-90d}
      - JWT_COOKIE_EXPIRES_IN=${JWT_COOKIE_EXPIRES_IN:-90}
      - CORS_ORIGIN=http://localhost:3000
      - CLIENT_ORIGIN=http://localhost:3000
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-change_this_password_immediately}

      # Hot reload
      - CHOKIDAR_USEPOLLING=true

    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev # For development only
      args:
        - REACT_APP_API_URL=http://localhost:5000/api/v1
    restart: always
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot reloading
      - FAST_REFRESH=true # I guess also hot reloading
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  # Mount source code for hot reloading
      - /app/node_modules  # Prevent overriding node_modules with host directory

volumes:
  mongo_data:
